name: Update GitHub Profile

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&hide_border=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&theme=tokyonight&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Trophies
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: username=${{ github.repository_owner }}&theme=tokyonight&column=7&margin-w=15&margin-h=15
          path: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: theme=tokyo-night&hide_border=true&area=true&radius=8
          output_path: activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Activity Graph
        run: |
          mkdir -p profile
          mv activity-graph.svg profile/activity-graph.svg

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/

          git commit -m "Update GitHub profile statistics" || exit 0

          git push
